import {AppRouterCacheProvider} from '@mui/material-nextjs/v14-appRouter';
import {CssBaseline, StyledEngineProvider} from '@mui/material';
import type {Metadata} from "next";
import {Inter} from "next/font/google";
import "./globals.css";
import NavBar from "@/components/NavBar";
import {AuthProvider} from "@/components/AuthProvider";
import {ColorModeProvider} from "@/components/ThemeContext";
import Container from "@mui/material/Container";
import React, {Suspense} from "react";
import Loading from "@/app/loading";
import NavTabs from "@/components/NavTabs";
import Footer from "@/components/Footer";

const inter = Inter({subsets: ["latin"]});

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({
                                       children,
                                   }: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en">
        <body className={inter.className}>
        <AppRouterCacheProvider>
            <StyledEngineProvider injectFirst>
                <ColorModeProvider>
                    <AuthProvider>
                        <CssBaseline/>
                        <NavBar/>
                        <Container maxWidth="lg">
                            <NavTabs/>
                            <Suspense fallback={<Loading/>}>
                                {children}
                            </Suspense>
                        </Container>
                        <Footer/>
                    </AuthProvider>
                </ColorModeProvider>
            </StyledEngineProvider>
        </AppRouterCacheProvider>
        </body>
        </html>
    );
}